
tasks:
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT=on-partial
    before: 
      cd /workspace
      curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
      sudo installer -pkg AWSCLIV2.pkg -target /
      cd /workspace/AWS-SAA

